# Generated by Django 4.1.4 on 2022-12-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questuin',
            new_name='question',
        ),
    ]
